name: CI/CD1
on: workflow_dispatch
jobs:
  build:
   outputs:
     Test: ${{ steps.step1.outputs.name }}
   runs-on: ubuntu-slim
   steps:
       - name: Call variable
         run: echo "name=Sagar" >> $GITHUB_OUTPUT
  deploy:
   needs: build
   runs-on: ubuntu-slim
   steps:
     - name: call output from build
       run: echo "Call name output from build ${{ needs.build.outputs.Test }}
      
