name: CI/CD
on:   
 push: 
   branches:
    - main
    - staging
jobs:
  build:
   runs-on: ubuntu-slim
   steps:
     - name: run if condition
       if: github.ref_name == 'staging'
       run: echo "running form main" 
      
