name: CI/CD
on: 
 workflow_dispatch:
   inputs:
     environment:
      required: true
      type: choice
      options:
        - dev
        - staging
        - prod
     artifact_tag:
      required: true
jobs:
  build:
   runs-on: ubuntu-slim
   steps:
     - name: print
       run: echo "hello tag ${{ inputs.artifact_tag }} deploy ${{ inputs.environment }}"
 
