name: CI/CD
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-slim
   steps:
     - name: Checkout Code
       uses: actions/checkout@v4
     - name: Print
       run: |
        cat "index.html"
        cat "index1.html"
